Give Users Access To waitForChromeToClose() Call
When users specify a `--user-data-dir=<path>` browser argument, `Launcher.waitForChromeToClose()` is not called and this causes  messages such as the following after the program has exited.

```
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
```

This is also a problem on Windows as it causes the exit code from `sys.exit(<code>)` to be clobbered with code 120 under some conditions.

This option will expose `waitForBrowserToClose` option to the Launcher.