Chromium download fixes (file not found)
Currently `pyppeteer-install` gives the following error when a Chromium downloadable is not found, which is confusing since it both says `chromium download done` and `zipfile.BadZipFile: File is not a zip file`:

```
[W:pyppeteer.chromium_downloader]
chromium download done.
Traceback (most recent call last):
[...]
zipfile.BadZipFile: File is not a zip file
```

This fix checks for HTTP errors, and if an error is found will generate a clear error. Here is an example obtained by setting PYPPETEER_CHROMIUM_REVISION to 1 (there's no revision 1):
```
[W:pyppeteer.chromium_downloader] Starting Chromium download. Download may take a few minutes.
Traceback (most recent call last):
[...]
OSError: Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1/chrome-win32.zip: Received <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromium-browser-snapshots/Win_x64/1/chrome-win32.zip</Details></Error>.
```

This pull request also incorporates pyppeteer#224 (Fix tqdm exception when NO_PROGRESS_BAR is True).

Finally, it closes a gaping man-in-the-middle security hole and defaults the code to security-first (duh!).